### PR TITLE
Fixed the initial server setup

### PR DESCRIPTION
**Pull request by wrejcodes**
Removed stuff from 424 in the server.js file. Updated .gitigore for using sqlite for development. Updated the package.json to remove the parse script from 424. Added instructions for using sqlite on the README.

### CODE REVIEW

**Review by Quinn-Donnelly — APPROVED** [review]
Looks good to me. Not sure if this works currently with no migrations in the migrations folder but once we have some work done should be fine.

**Comment by Quinn-Donnelly** [comment]
I will configure travis with this repo so that we have that for when people start working.

**Comment by wrejcodes** [comment]
Yeah it does give an error without a migrations folder but once we actually start generating migrations it should be fine.

**Comment by wrejcodes** [comment]
if you mkdir migrations on your end it doesn't throw an error or anything and just says there are no migrations to execute

**Comment by Quinn-Donnelly** [comment]
Sounds good then as long as we note that somewhere for when new people work on it. If this is still the case when they begin their work.

I'm good with the PR we can wait for @timthom64 to review and he can merge in.

**Comment by wrejcodes** [comment]
Since we're waiting I can go ahead and add the section about the migrations if you would like

**Review by Quinn-Donnelly — APPROVED** [review]

**Comment by wrejcodes** [comment]
Went ahead and made the fix to the sequelize-cli typo in the install section. Meant to do it earlier but totally forgot when until I saw your pull request this morning

**Comment by Quinn-Donnelly** [comment]
Ah yes I forgot we had this copied from there. Good catch.

**Review by tctcodes — APPROVED** [review]
Looks good. Good work!

**Comment by wrejcodes** [comment]
🙏

**Pull request merged**
